openapi: 3.1.0

info: 
  title: Tokener API,
  description: 
    This microservice aims to generate tokens for the clients, so they can use 
    the token to access any microservice on the company network. It is a simple 
    service that generates a token and stores it in a centralized database. 
    This microservice aims to solve the problem of generating tokens in 
    disparate environments, where each microservice has its own token generator.
  version: 1.0.0

servers: [
  - url: http://localhost:8000
  description: Local server
  
  url: http://tokener.orionsoft.site
  description: Remote server 
]

paths: 
  /: 
    get: 
      sumary: Returns the API presentation.
      description: 
        Its just a simple endpoint to show the API Presentation 
        in HTML for display in a web browser.

    responses: 
      200: 
        description: HTML containing the API Presentation
        content: text/html

  /reference: 
      get: 
        summary: Returns the API Reference.
        description: 
          Its just a simple endpoint to show the API Reference 
          in HTML for display in a web browser.
      
      responses:
        200:
          description: HTML containing the API Reference.
          content: text/html
        
  /token/{email}: 
      get: 
        summary: Returns an object containing information about the token.
        description: 
          A valid email address is required to get an existing token from the database. 
          If the email address is not found, a new token is generated and stored in the 
          database and sent to the client. The token should be used to grant access 
          to service. 

      responses:
        200:
          description: Returns the token related to the email.
          content: application/json
            schema: 
              type: object 

      
    
      
    
